# -*- coding: utf-8 -*-
"""transformer models (multi labels).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TE3PWzzZJn-zbcz63Z_a_2nt8SMMYEVT
"""

# ============================================================
# CELL 1 — TRAINING
# Upload: 8months_balanced_faults.xlsx, 8monthsdt_predictions.xlsx
# ============================================================

!pip install -q openpyxl

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import f1_score
import matplotlib.pyplot as plt
import pickle, os, warnings
warnings.filterwarnings('ignore')

DEVICE   = 'cuda' if torch.cuda.is_available() else 'cpu'
SAVE_DIR = '/content/tst_ckpt'
os.makedirs(SAVE_DIR, exist_ok=True)
print(f'Device: {DEVICE}')

# ── CONFIG ───────────────────────────────────────────────────
TRAIN_SENSOR_FILE = '/content/8monthsmultisensor_faults.xlsx'
TRAIN_DT_FILE     = '/content/8monthsdt_predictionsonly.xlsx'

SENSOR_COLS = ['T (degC)', 'Tdew (degC)', 'rh (%)']
DT_COLS     = ['T_pred',   'Td_pred',     'RH_pred']
TIMESTAMP   = 'Date Time'
LABEL_COL   = 'binary_label'

# WHY these values:
# Faults are SHORT BURSTS of ~3-5 timesteps scattered through clean readings.
# W=64 caused every window to contain both classes equally → majority vote = noise → ~53% acc.
# W=16 (2.7 hrs context) captures a full fault burst with surrounding clean context.
# Per-timestep prediction: TST sees 16 steps of context, outputs a label for EVERY step.
WINDOW_SIZE = 16    # 16 steps × 10 min = 2.7 hrs of context
STRIDE      = 4     # 75% overlap → dense coverage of fault boundaries
ROLL_W      = 6     # rolling stats window = 1 hr context for residual features

D_MODEL    = 64
N_HEADS    = 4      # D_MODEL must be divisible by N_HEADS
N_LAYERS   = 3
D_FF       = 128
DROPOUT    = 0.1
BATCH_SIZE = 256
EPOCHS     = 50
LR         = 3e-3
VAL_SPLIT  = 0.15
PATIENCE   = 8
SEED       = 42
# ────────────────────────────────────────────────────────────

torch.manual_seed(SEED); np.random.seed(SEED)


# ── 1. Load & align ──────────────────────────────────────────
sens = pd.read_excel(TRAIN_SENSOR_FILE)
dt   = pd.read_excel(TRAIN_DT_FILE)
sens[TIMESTAMP] = pd.to_datetime(sens[TIMESTAMP], dayfirst=True)
dt[TIMESTAMP]   = pd.to_datetime(dt[TIMESTAMP])

df = pd.merge(
    sens[[TIMESTAMP] + SENSOR_COLS + [LABEL_COL]],
    dt[[TIMESTAMP]   + DT_COLS],
    on=TIMESTAMP, how='inner'
).sort_values(TIMESTAMP).reset_index(drop=True)

print(f'Rows after merge: {len(df):,}')
print(f'Labels: {df[LABEL_COL].value_counts().to_dict()}')


# ── 2. Feature engineering ───────────────────────────────────
# For each sensor: residual + rolling stats on residual + sensor delta
# This gives the TST strong signals to detect drift (roll_mean grows),
# spikes (res_abs spikes), stuck_at (delta=0, res grows), replay (large res).

def build_features(df, sensor_cols, dt_cols, roll_w):
    cols, names = [], []
    for sc, dc in zip(sensor_cols, dt_cols):
        px  = sc.split()[0]
        res = df[sc] - df[dc]
        cols += [
            res.values,
            res.abs().values,
            (res**2).values,
            res.rolling(roll_w, min_periods=1).mean().values,
            res.rolling(roll_w, min_periods=1).std().fillna(0).values,
            res.abs().rolling(roll_w, min_periods=1).max().values,
            df[sc].diff().fillna(0).values,   # rate of change of raw sensor
        ]
        names += [f'{px}_res', f'{px}_res_abs', f'{px}_res_sq',
                  f'{px}_roll_mean', f'{px}_roll_std', f'{px}_roll_max', f'{px}_delta']
    return np.stack(cols, axis=1).astype(np.float32), names

X_raw, feat_names = build_features(df, SENSOR_COLS, DT_COLS, ROLL_W)
y_all  = df[LABEL_COL].values.astype(np.int64)
N_FEAT = X_raw.shape[1]
print(f'Features ({N_FEAT}): {feat_names}')

scaler   = StandardScaler()
X_scaled = scaler.fit_transform(X_raw).astype(np.float32)

pickle.dump(scaler,     open(f'{SAVE_DIR}/scaler.pkl',  'wb'))
pickle.dump(feat_names, open(f'{SAVE_DIR}/feats.pkl',   'wb'))
pickle.dump({'W': WINDOW_SIZE, 'S': STRIDE, 'F': N_FEAT, 'ROLL_W': ROLL_W,
             'D': D_MODEL, 'H': N_HEADS, 'L': N_LAYERS, 'FF': D_FF, 'DO': DROPOUT},
            open(f'{SAVE_DIR}/cfg.pkl', 'wb'))


# ── 3. Dataset ───────────────────────────────────────────────
# KEY CHANGE from v1: predict label for EVERY timestep in the window.
# The TST sees 16 steps of context and outputs 16 predictions.
# This is fundamentally better for short fault bursts (avg 3-5 steps).

class FaultDataset(Dataset):
    def __init__(self, X, y, W, S):
        wins, labs = [], []
        for s in range(0, len(X) - W + 1, S):
            wins.append(X[s:s+W])
            labs.append(y[s:s+W])         # (W,) — label every timestep
        self.X = torch.tensor(np.stack(wins), dtype=torch.float32)  # (N, W, F)
        self.y = torch.tensor(np.stack(labs), dtype=torch.long)     # (N, W)
    def __len__(self):          return len(self.y)
    def __getitem__(self, idx): return self.X[idx], self.y[idx]

full_ds = FaultDataset(X_scaled, y_all, WINDOW_SIZE, STRIDE)
n_val   = int(len(full_ds) * VAL_SPLIT)
n_train = len(full_ds) - n_val
train_ds, val_ds = torch.utils.data.random_split(
    full_ds, [n_train, n_val], generator=torch.Generator().manual_seed(SEED)
)
train_loader = DataLoader(train_ds, BATCH_SIZE, shuffle=True,  num_workers=2, pin_memory=True)
val_loader   = DataLoader(val_ds,   BATCH_SIZE, shuffle=False, num_workers=2, pin_memory=True)
print(f'Windows — train: {n_train:,}  val: {n_val:,}')


# ── 4. TST ───────────────────────────────────────────────────
class PositionalEncoding(nn.Module):
    def __init__(self, d, max_len=512, drop=0.1):
        super().__init__()
        self.drop = nn.Dropout(drop)
        pe  = torch.zeros(max_len, d)
        pos = torch.arange(0, max_len).unsqueeze(1).float()
        div = torch.exp(torch.arange(0, d, 2).float() * (-np.log(10000.0) / d))
        pe[:, 0::2] = torch.sin(pos * div)
        pe[:, 1::2] = torch.cos(pos * div)
        self.register_buffer('pe', pe.unsqueeze(0))
    def forward(self, x): return self.drop(x + self.pe[:, :x.size(1)])

class TST(nn.Module):
    """
    Temporal Signal Transformer — per-timestep binary fault detection.

    Input  : (B, W, F)  — window of residual-augmented features
    Output : (B, W, 2)  — logits for every timestep in the window

    This per-timestep output is the critical fix:
    instead of one label per window (which averaged away short faults),
    we predict a label at every position, giving the TST local context
    while still classifying each individual timestep.
    """
    def __init__(self, n_feat, d, n_heads, n_layers, d_ff, drop):
        super().__init__()
        self.proj = nn.Sequential(nn.Linear(n_feat, d), nn.LayerNorm(d))
        self.pe   = PositionalEncoding(d, drop=drop)
        enc = nn.TransformerEncoderLayer(d, n_heads, d_ff, drop,
                                          batch_first=True, norm_first=True)
        self.enc  = nn.TransformerEncoder(enc, n_layers, enable_nested_tensor=False)
        self.head = nn.Sequential(
            nn.LayerNorm(d),
            nn.Linear(d, d // 2),
            nn.GELU(),
            nn.Dropout(drop),
            nn.Linear(d // 2, 2)     # 2 classes at every timestep
        )
    def forward(self, x):            # x: (B, W, F)
        x = self.proj(x)             # (B, W, d)
        x = self.pe(x)
        x = self.enc(x)              # (B, W, d)
        return self.head(x)          # (B, W, 2)  ← every timestep gets logits

model = TST(N_FEAT, D_MODEL, N_HEADS, N_LAYERS, D_FF, DROPOUT).to(DEVICE)
n_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f'\nTST | features={N_FEAT} → d={D_MODEL} | layers={N_LAYERS} | params={n_params:,}')


# ── 5. Loss, optimiser ───────────────────────────────────────
# FocalLoss focuses on hard borderline timesteps (fault boundary steps)
class FocalLoss(nn.Module):
    def __init__(self, gamma=2.0):
        super().__init__()
        self.gamma = gamma
    def forward(self, logits, targets):
        # logits: (B*W, 2)  targets: (B*W,)
        ce = nn.functional.cross_entropy(logits, targets, reduction='none')
        return ((1 - torch.exp(-ce)) ** self.gamma * ce).mean()

criterion = FocalLoss(gamma=2.0)
optimizer = torch.optim.AdamW(model.parameters(), lr=LR, weight_decay=1e-4)
scheduler = torch.optim.lr_scheduler.OneCycleLR(
    optimizer, max_lr=LR, steps_per_epoch=len(train_loader), epochs=EPOCHS
)


# ── 6. Train / val loop ──────────────────────────────────────
def run_epoch(loader, train=True):
    model.train() if train else model.eval()
    total_loss, all_p, all_y = 0.0, [], []
    ctx = torch.enable_grad() if train else torch.no_grad()
    with ctx:
        for xb, yb in loader:
            xb, yb = xb.to(DEVICE), yb.to(DEVICE)      # (B,W,F), (B,W)
            logits = model(xb)                           # (B,W,2)
            B, W, C = logits.shape
            loss = criterion(logits.reshape(B*W, C), yb.reshape(B*W))
            if train:
                optimizer.zero_grad(); loss.backward()
                nn.utils.clip_grad_norm_(model.parameters(), 1.0)
                optimizer.step(); scheduler.step()
            total_loss += loss.item() * B * W
            all_p.append(logits.reshape(B*W, C).argmax(1).cpu())
            all_y.append(yb.reshape(B*W).cpu())
    p = torch.cat(all_p).numpy(); y = torch.cat(all_y).numpy()
    return total_loss / len(y), (p==y).mean(), f1_score(y, p, zero_division=0)

hist = {'tl':[],'vl':[],'ta':[],'va':[],'tf':[],'vf':[]}
best_f1, pat = -1.0, 0

print(f'\n{"Ep":>4} | {"TrLoss":>8} {"TrAcc":>7} {"TrF1":>6} | {"VaLoss":>8} {"VaAcc":>7} {"VaF1":>6}')
print('─' * 65)

for ep in range(1, EPOCHS+1):
    tl, ta, tf = run_epoch(train_loader, train=True)
    vl, va, vf = run_epoch(val_loader,   train=False)
    for k,v in zip(['tl','ta','tf','vl','va','vf'],[tl,ta,tf,vl,va,vf]):
        hist[k].append(v)
    print(f'{ep:>4} | {tl:>8.4f} {ta:>6.2%} {tf:>6.4f} | {vl:>8.4f} {va:>6.2%} {vf:>6.4f}', end='')
    if vf > best_f1:
        best_f1 = vf
        torch.save(model.state_dict(), f'{SAVE_DIR}/best_model.pt')
        pat = 0; print('  ✔')
    else:
        pat += 1; print(f'  ({pat}/{PATIENCE})')
        if pat >= PATIENCE: print(f'Early stop at ep {ep}.'); break

print(f'\nBest val F1: {best_f1:.4f}')

fig, axes = plt.subplots(1, 3, figsize=(14, 4))
for ax, (tk, vk, title) in zip(axes, [('tl','vl','Loss'),('ta','va','Accuracy'),('tf','vf','F1')]):
    ax.plot(hist[tk], label='Train'); ax.plot(hist[vk], label='Val')
    ax.set_title(title); ax.legend(); ax.grid(alpha=0.3)
plt.suptitle('TST Training Curves'); plt.tight_layout(); plt.show()
print(f'✅ Saved to {SAVE_DIR}')

